### ISSUE TITLE
Add a hook for when the connection ends.

### ISSUE THREAD

**Issue by royvandewater** [computes/ipfs-http-api#4]
There's no good way to see if a connection has terminated server side (Such as an IPFS crash). Right now, the only outward indication that the connection has terminated is that channel is closed. However, you can't check to see if the channel is closed without doing a blocking read. 

We could add a third channel that only emits once the connection has closed. We may want to consider returning a struct from `Subscribe` instead of 3 chans and an error, as described in #3

**Comment by MrGossett** [comment]
looks like this was closed in PR #5
